/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Query Service
 * Query Service Api Documentation
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ADAttribute
 */
export interface ADAttribute {
    /**
     * 
     * @type {string}
     * @memberof ADAttribute
     */
    ad_attribute?: string;
    /**
     * 
     * @type {string}
     * @memberof ADAttribute
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ADAttribute
     */
    usage?: string;
}


