/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Query Service
 * Query Service Api Documentation
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogGroupView } from './catalog-group-view';

/**
 * 
 * @export
 * @interface CatalogGroupDetailArray
 */
export interface CatalogGroupDetailArray {
    /**
     * 
     * @type {number}
     * @memberof CatalogGroupDetailArray
     */
    recordSetCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CatalogGroupDetailArray
     */
    recordSetTotal?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CatalogGroupDetailArray
     */
    recordSetComplete?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CatalogGroupDetailArray
     */
    recordSetStartNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof CatalogGroupDetailArray
     */
    resourceName?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogGroupDetailArray
     */
    resourceId?: string;
    /**
     * 
     * @type {number}
     * @memberof CatalogGroupDetailArray
     */
    uniqueId?: number;
    /**
     * 
     * @type {Array<CatalogGroupView>}
     * @memberof CatalogGroupDetailArray
     */
    catalogGroupView?: Array<CatalogGroupView>;
}


