/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Query Service
 * Query Service Api Documentation
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserDataType } from './user-data-type';

/**
 * 
 * @export
 * @interface ProductSuggestionEntry
 */
export interface ProductSuggestionEntry {
    /**
     * 
     * @type {boolean}
     * @memberof ProductSuggestionEntry
     */
    hasSingleSKU?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductSuggestionEntry
     */
    resourceId?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSuggestionEntry
     */
    uniqueID?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSuggestionEntry
     */
    partNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSuggestionEntry
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSuggestionEntry
     */
    thumbnail?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSuggestionEntry
     */
    storeID?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSuggestionEntry
     */
    name?: string;
    /**
     * 
     * @type {UserDataType}
     * @memberof ProductSuggestionEntry
     */
    userData?: UserDataType;
}


