/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Query Service
 * Query Service Api Documentation
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ADAttribute } from './adattribute';
import { Attribute } from './attribute';
import { MetaData } from './meta-data';
import { Price } from './price';
import { UserDataType } from './user-data-type';

/**
 * 
 * @export
 * @interface ProductSummary
 */
export interface ProductSummary {
    /**
     * 
     * @type {Array<ADAttribute>}
     * @memberof ProductSummary
     */
    ad_attribute?: Array<ADAttribute>;
    /**
     * 
     * @type {Array<Attribute>}
     * @memberof ProductSummary
     */
    attributes?: Array<Attribute>;
    /**
     * 
     * @type {Array<UserDataType>}
     * @memberof ProductSummary
     */
    userData?: Array<UserDataType>;
    /**
     * 
     * @type {Array<Price>}
     * @memberof ProductSummary
     */
    price?: Array<Price>;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    numberOfSKUs?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSummary
     */
    disallowRecurringOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    manufacturer?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductSummary
     */
    parentCatalogGroupID?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSummary
     */
    uniqueID?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    partNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    thumbnail?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    longDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    keyword?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSummary
     */
    hasSingleSKU?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSummary
     */
    hasSingleSKUESet?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    singleSKUCatalogEntryID?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    storeID?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    fullImage?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    parentCatalogEntryID?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    subscriptionTypeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    dynamicKitURL?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    dynamicKitDefaultConfiguration?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSummary
     */
    dynamicKitDefaultConfigurationComplete?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSummary
     */
    dynamicKitDefaultConfigurationCompleteESet?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    dynamicKitModelReference?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    metaDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    metaKeyword?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    fullImageAltDescription?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSummary
     */
    buyable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    catalogEntryTypeCode?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSummary
     */
    recordSetCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductSummary
     */
    recordSetTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductSummary
     */
    recordSetTotalMatches?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSummary
     */
    recordSetComplete?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProductSummary
     */
    recordSetStartNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    resourceName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummary
     */
    resourceId?: string;
    /**
     * 
     * @type {MetaData}
     * @memberof ProductSummary
     */
    metaData?: MetaData;
}


