/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Query Service
 * Query Service Api Documentation
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BreadCrumbTrailEntryView } from './bread-crumb-trail-entry-view';
import { FacetView } from './facet-view';
import { ProductDetail } from './product-detail';

/**
 * 
 * @export
 * @interface ProductDetailArray
 */
export interface ProductDetailArray {
    /**
     * 
     * @type {Array<ProductDetail>}
     * @memberof ProductDetailArray
     */
    catalogEntryView?: Array<ProductDetail>;
    /**
     * 
     * @type {Array<FacetView>}
     * @memberof ProductDetailArray
     */
    facetView?: Array<FacetView>;
    /**
     * 
     * @type {Array<BreadCrumbTrailEntryView>}
     * @memberof ProductDetailArray
     */
    breadCrumbTrailEntryView?: Array<BreadCrumbTrailEntryView>;
    /**
     * 
     * @type {object}
     * @memberof ProductDetailArray
     */
    breadCrumbTrailEntryViewExtended?: object;
}


