#==================================================
# Licensed Materials - Property of HCL Technologies
#
# HCL Commerce
#
# (C) Copyright HCL Technologies Limited 2020
#
#==================================================

# prettier config yaml file
tabWidth: 2
endOfLine: "lf"
jsxBracketSameLine: true
trailingComma: "es5"
arrowParens: "always"
printWidth: 120
