/*
 *---------------------------------------------------
 * Licensed Materials - Property of HCL Technologies
 *
 * HCL Commerce
 *
 * (C) Copyright HCL Technologies Limited 2020
 *
 *---------------------------------------------------
 */
//Standard libraries
import { createAction } from "@reduxjs/toolkit";
//Redux
import * as ACTIONTYPES from "../action-types/order";

const ADD_ITEM_ACTION = createAction<any, string>(
  ACTIONTYPES.ITEM_ADD_REQUESTED
);
const REMOVE_ITEM_ACTION = createAction<any, string>(
  ACTIONTYPES.ITEM_REMOVE_REQUESTED
);
const UPDATE_ITEM_ACTION = createAction<any, string>(
  ACTIONTYPES.ITEM_UPDATE_REQUESTED
);
const GET_CART_ACTION = createAction<any, string>(
  ACTIONTYPES.CART_GET_REQUESTED
);
const CART_SUBMIT_ERROR_ACTION = createAction<any, string>(
  ACTIONTYPES.ORDER_PLACE_ERROR
);

const COPY_CART_ACTION = createAction<any, string>(ACTIONTYPES.COPY_CART);
const COPY_CART_SUCCESS_ACTION = createAction<any, string>(
  ACTIONTYPES.COPY_CART_SUCCESS
);
const COPY_CART_ERROR_ACTION = createAction<any, string>(
  ACTIONTYPES.COPY_CART_ERROR
);

const GET_SHIPINFO_ACTION = createAction<any, string>(
  ACTIONTYPES.SHIPINFO_GET_REQUESTED
);

const UPDATE_SHIPINFO_ACTION = createAction<any, string>(
  ACTIONTYPES.SHIPINFO_UPDATE_REQUESTED
);

const GET_SHIPMODES_ACTION = createAction<any, string>(
  ACTIONTYPES.SHIPMODES_GET_REQUESTED
);

const UPDATE_SHIPMODE_ACTION = createAction<any, string>(
  ACTIONTYPES.SHIPMODE_UPDATE_REQUESTED
);

const UPDATE_SHIPMODE_AND_ADD_PI_ACTION = createAction<any, string>(
  ACTIONTYPES.SHIPMODE_UPDATE_AND_PI_ADD_REQUESTED
);

const GET_PAYMETHODS_ACTION = createAction<any, string>(
  ACTIONTYPES.PAYMETHODS_GET_REQUESTED
);

const ADD_PI_ACTION = createAction<any, string>(ACTIONTYPES.PI_ADD_REQUESTED);

const PLACE_ORDER_ACTION = createAction<any, string>(
  ACTIONTYPES.ORDER_PLACE_REQUESTED
);

const NEXT_CHECKOUTSTEP_ACTION = createAction(
  ACTIONTYPES.CHECKOUTSTEP_NEXT_REQUESTED
);

const PREV_CHECKOUTSTEP_ACTION = createAction(
  ACTIONTYPES.CHECKOUTSTEP_PREV_REQUESTED
);

const RESET_CHECKOUTSTEP_ACTION = createAction(
  ACTIONTYPES.CHECKOUTSTEP_RESET_REQUESTED
);

const RESET_CART_ACTION = createAction(ACTIONTYPES.CART_RESET_REQUESTED);

const TOGGLE_RECURRINGORDER_ACTION = createAction(
  ACTIONTYPES.RECURRINGORDER_TOGGLE_REQUESTED
);

const SET_RECURRINGORDER_FREQ_ACTION = createAction<string>(
  ACTIONTYPES.RECURRINGORDER_FREQ_SET_REQUESTED
);

const SET_RECURRINGORDER_STARTDATE_ACTION = createAction<any>(
  ACTIONTYPES.RECURRINGORDER_STARTDATE_SET_REQUESTED
);

const PLACE_RECURRINGORDER_ACTION = createAction<any>(
  ACTIONTYPES.RECURRINGORDER_PLACE_REQUESTED
);

export {
  ADD_ITEM_ACTION,
  REMOVE_ITEM_ACTION,
  UPDATE_ITEM_ACTION,
  GET_CART_ACTION,
  CART_SUBMIT_ERROR_ACTION,
  GET_SHIPINFO_ACTION,
  UPDATE_SHIPINFO_ACTION,
  GET_SHIPMODES_ACTION,
  UPDATE_SHIPMODE_ACTION,
  UPDATE_SHIPMODE_AND_ADD_PI_ACTION,
  GET_PAYMETHODS_ACTION,
  ADD_PI_ACTION,
  PLACE_ORDER_ACTION,
  COPY_CART_ACTION,
  COPY_CART_SUCCESS_ACTION,
  COPY_CART_ERROR_ACTION,
  NEXT_CHECKOUTSTEP_ACTION,
  PREV_CHECKOUTSTEP_ACTION,
  RESET_CHECKOUTSTEP_ACTION,
  RESET_CART_ACTION,
  TOGGLE_RECURRINGORDER_ACTION,
  SET_RECURRINGORDER_FREQ_ACTION,
  SET_RECURRINGORDER_STARTDATE_ACTION,
  PLACE_RECURRINGORDER_ACTION,
};
