/* tslint:disable */
/* eslint-disable */
/**
 * API definitions for Seller organization requests approval service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './address';

/**
 * 
 * @export
 * @interface SellerOrganizationRequest
 */
export interface SellerOrganizationRequest {
    /**
     * 
     * @type {number}
     * @memberof SellerOrganizationRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SellerOrganizationRequest
     */
    submitterEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof SellerOrganizationRequest
     */
    organizationName?: string;
    /**
     * 
     * @type {number}
     * @memberof SellerOrganizationRequest
     */
    storeId?: number;
    /**
     * 
     * @type {string}
     * @memberof SellerOrganizationRequest
     */
    storeIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof SellerOrganizationRequest
     */
    createDate?: string;
    /**
     * 
     * @type {string}
     * @memberof SellerOrganizationRequest
     */
    status?: string;
    /**
     * 
     * @type {Address}
     * @memberof SellerOrganizationRequest
     */
    organizationAddress?: Address;
}


