/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartUsablePaymentInformation } from './cart-usable-payment-information';
import { ComIbmCommerceFoundationCommonDatatypesPersonIdentifierType } from './com-ibm-commerce-foundation-common-datatypes-person-identifier-type';
import { ComIbmCommerceFoundationCommonDatatypesQuoteIdentifierType } from './com-ibm-commerce-foundation-common-datatypes-quote-identifier-type';
import { ComIbmCommerceOrderFacadeDatatypesAdjustmentRequirementType } from './com-ibm-commerce-order-facade-datatypes-adjustment-requirement-type';
import { ComIbmCommerceOrderFacadeDatatypesCSRCommentsType } from './com-ibm-commerce-order-facade-datatypes-csrcomments-type';
import { ComIbmCommerceOrderFacadeDatatypesChannelType } from './com-ibm-commerce-order-facade-datatypes-channel-type';
import { ComIbmCommerceOrderFacadeDatatypesCouponCodeType } from './com-ibm-commerce-order-facade-datatypes-coupon-code-type';
import { ComIbmCommerceOrderFacadeDatatypesOrderBLockInfoType } from './com-ibm-commerce-order-facade-datatypes-order-block-info-type';
import { ComIbmCommerceOrderFacadeDatatypesPromotionCodeType } from './com-ibm-commerce-order-facade-datatypes-promotion-code-type';

/**
 * 
 * @export
 * @interface CartUsablePaymentInfo
 */
export interface CartUsablePaymentInfo {
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesPersonIdentifierType}
     * @memberof CartUsablePaymentInfo
     */
    orderEditor?: ComIbmCommerceFoundationCommonDatatypesPersonIdentifierType;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    quoteID?: string;
    /**
     * 
     * @type {Array<ComIbmCommerceOrderFacadeDatatypesCouponCodeType>}
     * @memberof CartUsablePaymentInfo
     */
    couponCode?: Array<ComIbmCommerceOrderFacadeDatatypesCouponCodeType>;
    /**
     * 
     * @type {Array<ComIbmCommerceOrderFacadeDatatypesCSRCommentsType>}
     * @memberof CartUsablePaymentInfo
     */
    cSRComments?: Array<ComIbmCommerceOrderFacadeDatatypesCSRCommentsType>;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    externalOrderID?: string;
    /**
     * 
     * @type {Array<CartUsablePaymentInformation>}
     * @memberof CartUsablePaymentInfo
     */
    usablePaymentInformation?: Array<CartUsablePaymentInformation>;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    comments?: string;
    /**
     * 
     * @type {Array<ComIbmCommerceOrderFacadeDatatypesAdjustmentRequirementType>}
     * @memberof CartUsablePaymentInfo
     */
    adjustmentRequirement?: Array<ComIbmCommerceOrderFacadeDatatypesAdjustmentRequirementType>;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    lastUpdateDate?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesQuoteIdentifierType}
     * @memberof CartUsablePaymentInfo
     */
    quoteIdentifier?: ComIbmCommerceFoundationCommonDatatypesQuoteIdentifierType;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    shipAsComplete?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    buyerPONumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    customerOrderNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    placedDate?: string;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesOrderBLockInfoType}
     * @memberof CartUsablePaymentInfo
     */
    bLockInfo?: ComIbmCommerceOrderFacadeDatatypesOrderBLockInfoType;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInfo
     */
    orderVersion?: string;
    /**
     * 
     * @type {Array<ComIbmCommerceOrderFacadeDatatypesPromotionCodeType>}
     * @memberof CartUsablePaymentInfo
     */
    promotionCode?: Array<ComIbmCommerceOrderFacadeDatatypesPromotionCodeType>;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesChannelType}
     * @memberof CartUsablePaymentInfo
     */
    channel?: ComIbmCommerceOrderFacadeDatatypesChannelType;
}


