/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartRewardOptionRewardSpecificationGiftSetSpecificationGiftItemCatalogEntryIdentifierExternalIdentifier } from './cart-reward-option-reward-specification-gift-set-specification-gift-item-catalog-entry-identifier-external-identifier';

/**
 * 
 * @export
 * @interface CartRewardOptionRewardSpecificationGiftSetSpecificationGiftItemCatalogEntryIdentifier
 */
export interface CartRewardOptionRewardSpecificationGiftSetSpecificationGiftItemCatalogEntryIdentifier {
    /**
     * 
     * @type {string}
     * @memberof CartRewardOptionRewardSpecificationGiftSetSpecificationGiftItemCatalogEntryIdentifier
     */
    uniqueID?: string;
    /**
     * 
     * @type {CartRewardOptionRewardSpecificationGiftSetSpecificationGiftItemCatalogEntryIdentifierExternalIdentifier}
     * @memberof CartRewardOptionRewardSpecificationGiftSetSpecificationGiftItemCatalogEntryIdentifier
     */
    externalIdentifier?: CartRewardOptionRewardSpecificationGiftSetSpecificationGiftItemCatalogEntryIdentifierExternalIdentifier;
}


