/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartRewardOptionGiftSetGiftItem } from './cart-reward-option-gift-set-gift-item';

/**
 * 
 * @export
 * @interface CartRewardOptionGiftSet
 */
export interface CartRewardOptionGiftSet {
    /**
     * 
     * @type {Array<CartRewardOptionGiftSetGiftItem>}
     * @memberof CartRewardOptionGiftSet
     */
    giftItem?: Array<CartRewardOptionGiftSetGiftItem>;
}


