/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartUsableShippingModeUserDataField } from './cart-usable-shipping-mode-user-data-field';

/**
 * 
 * @export
 * @interface CartUsableShippingMode
 */
export interface CartUsableShippingMode {
    /**
     * 
     * @type {string}
     * @memberof CartUsableShippingMode
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsableShippingMode
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsableShippingMode
     */
    storeId?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsableShippingMode
     */
    trackingURL?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsableShippingMode
     */
    carrier?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsableShippingMode
     */
    shipModeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsableShippingMode
     */
    shipModeId?: string;
    /**
     * 
     * @type {Array<CartUsableShippingModeUserDataField>}
     * @memberof CartUsableShippingMode
     */
    userDataField?: Array<CartUsableShippingModeUserDataField>;
}


