/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogIBMAdminDetailsItemDescriptionAttributes } from './catalog-ibmadmin-details-item-description-attributes';
import { CatalogIBMAdminDetailsItemDescriptionOverride } from './catalog-ibmadmin-details-item-description-override';

/**
 * 
 * @export
 * @interface CatalogIBMAdminDetailsItemDescription
 */
export interface CatalogIBMAdminDetailsItemDescription {
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    keyword?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    fullImage?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    longDescription?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    breadcrumb?: Array<string>;
    /**
     * 
     * @type {Array<CatalogIBMAdminDetailsItemDescriptionOverride>}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    override?: Array<CatalogIBMAdminDetailsItemDescriptionOverride>;
    /**
     * 
     * @type {Array<CatalogIBMAdminDetailsItemDescriptionAttributes>}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    attributes?: Array<CatalogIBMAdminDetailsItemDescriptionAttributes>;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    thumbnail?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescription
     */
    name?: string;
}


