/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAssetAttachmentAssetIdentifier } from './catalog-ibmadmin-details-item-attachment-reference-attachment-asset-attachment-asset-identifier';
import { CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAssetStoreIdentifier } from './catalog-ibmadmin-details-item-attachment-reference-attachment-asset-store-identifier';
import { CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAssetUserData } from './catalog-ibmadmin-details-item-attachment-reference-attachment-asset-user-data';

/**
 * 
 * @export
 * @interface CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
 */
export interface CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset {
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
     */
    mimeType?: string;
    /**
     * 
     * @type {CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAssetAttachmentAssetIdentifier}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
     */
    attachmentAssetIdentifier?: CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAssetAttachmentAssetIdentifier;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
     */
    rootDirectory?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
     */
    language?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
     */
    directoryPath?: string;
    /**
     * 
     * @type {CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAssetStoreIdentifier}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
     */
    storeIdentifier?: CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAssetStoreIdentifier;
    /**
     * 
     * @type {boolean}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
     */
    localAsset?: boolean;
    /**
     * 
     * @type {CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAssetUserData}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
     */
    userData?: CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAssetUserData;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset
     */
    attachmentAssetPath: string;
}


