/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryIBMAdminDetailsBreadcrumbItemAssociationCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifierExternalIdentifier } from './category-ibmadmin-details-breadcrumb-item-association-catalog-group-reference-catalog-group-identifier-external-identifier-store-identifier-external-identifier';

/**
 * 
 * @export
 * @interface CategoryIBMAdminDetailsBreadcrumbItemAssociationCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifier
 */
export interface CategoryIBMAdminDetailsBreadcrumbItemAssociationCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifier {
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAssociationCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifier
     */
    uniqueID?: string;
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemAssociationCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifierExternalIdentifier}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAssociationCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifier
     */
    externalIdentifier?: CategoryIBMAdminDetailsBreadcrumbItemAssociationCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifierExternalIdentifier;
}


