/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressEmailAddress1UserDataUserDataField } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-registrant-type-registrant-address-email-address1-user-data-user-data-field';

/**
 * 
 * @export
 * @interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressEmailAddress1UserData
 */
export interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressEmailAddress1UserData {
    /**
     * 
     * @type {Array<ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressEmailAddress1UserDataUserDataField>}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressEmailAddress1UserData
     */
    userDataField?: Array<ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressEmailAddress1UserDataUserDataField>;
}


