/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifierExternalIdentifier } from './com-ibm-commerce-order-facade-datatypes-promotion-code-type-associated-promotion-promotion-identifier-calculation-code-identifier-calculation-code-external-identifier-store-identifier-external-identifier';

/**
 * 
 * @export
 * @interface ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifier
 */
export interface ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifier {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifier
     */
    uniqueID?: string;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifierExternalIdentifier}
     * @memberof ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifier
     */
    externalIdentifier?: ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifierExternalIdentifier;
}


