/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Delete context attribute response.
 * @export
 * @interface ComIbmCommerceRestMemberHandlerPersonHandlerDeleteContextAttribute
 */
export interface ComIbmCommerceRestMemberHandlerPersonHandlerDeleteContextAttribute {
    /**
     * The user identifier list.
     * @type {Array<string>}
     * @memberof ComIbmCommerceRestMemberHandlerPersonHandlerDeleteContextAttribute
     */
    userId: Array<string>;
    /**
     * The address identifier list.
     * @type {Array<string>}
     * @memberof ComIbmCommerceRestMemberHandlerPersonHandlerDeleteContextAttribute
     */
    addressId: Array<string>;
}


