/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone1UserData } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-registrant-type-registrant-address-telephone1-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone1
 */
export interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone1 {
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone1UserData}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone1
     */
    userData?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone1UserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone1
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone1
     */
    value: string;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone1
     */
    publish?: boolean;
}


