/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansUserProfile
 */
export interface ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansUserProfile {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansUserProfile
     */
    preferredCommunication?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansUserProfile
     */
    preferredMeasure?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansUserProfile
     */
    displayName?: string;
    /**
     * A string used to identify the user for taxation purposes.
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansUserProfile
     */
    taxPayerId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansUserProfile
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansUserProfile
     */
    preferredDelivery?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansUserProfile
     */
    receiveSMSNotification?: string;
}


