/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddressUserData } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-purchaser-address-address-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
 */
export interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
     */
    city?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
     */
    addressLine?: Array<string>;
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddressUserData}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
     */
    userData?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddressUserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
     */
    country?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
     */
    primary?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
     */
    stateOrProvinceName?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressAddress
     */
    internalOfficeAddress?: string;
}


