/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceRestPriceHandlerPriceHandlerPriceRequestQuery } from './com-ibm-commerce-rest-price-handler-price-handler-price-request-query';

/**
 * Price request.
 * @export
 * @interface ComIbmCommerceRestPriceHandlerPriceHandlerPriceRequest
 */
export interface ComIbmCommerceRestPriceHandlerPriceHandlerPriceRequest {
    /**
     * 
     * @type {ComIbmCommerceRestPriceHandlerPriceHandlerPriceRequestQuery}
     * @memberof ComIbmCommerceRestPriceHandlerPriceHandlerPriceRequest
     */
    query: ComIbmCommerceRestPriceHandlerPriceHandlerPriceRequestQuery;
}


