/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierTypeCalculationCodeIdentifier } from './com-ibm-commerce-foundation-common-datatypes-promotion-identifier-type-calculation-code-identifier';
import { ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierTypeExternalIdentifier } from './com-ibm-commerce-foundation-common-datatypes-promotion-identifier-type-external-identifier';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierType
 */
export interface ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierType {
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierTypeCalculationCodeIdentifier}
     * @memberof ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierType
     */
    calculationCodeIdentifier?: ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierTypeCalculationCodeIdentifier;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierType
     */
    uniqueID?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierTypeExternalIdentifier}
     * @memberof ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierType
     */
    externalIdentifier?: ComIbmCommerceFoundationCommonDatatypesPromotionIdentifierTypeExternalIdentifier;
}


