/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfoDuration } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-fulfillment-schedule-end-info-duration';
import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfoUserData } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-fulfillment-schedule-end-info-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfo
 */
export interface ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfo {
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfoDuration}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfo
     */
    duration?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfoDuration;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfo
     */
    totalOccurrences?: number;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfo
     */
    endDate?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfoUserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfo
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfoUserData;
}


