/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesStoreIdentifierTypeExternalIdentifier } from './com-ibm-commerce-foundation-common-datatypes-store-identifier-type-external-identifier';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesStoreIdentifierType
 */
export interface ComIbmCommerceFoundationCommonDatatypesStoreIdentifierType {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesStoreIdentifierType
     */
    uniqueID?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesStoreIdentifierTypeExternalIdentifier}
     * @memberof ComIbmCommerceFoundationCommonDatatypesStoreIdentifierType
     */
    externalIdentifier?: ComIbmCommerceFoundationCommonDatatypesStoreIdentifierTypeExternalIdentifier;
}


