/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesRewardOptionTypeUserDataUserDataField } from './com-ibm-commerce-order-facade-datatypes-reward-option-type-user-data-user-data-field';

/**
 * 
 * @export
 * @interface ComIbmCommerceOrderFacadeDatatypesRewardOptionTypeUserData
 */
export interface ComIbmCommerceOrderFacadeDatatypesRewardOptionTypeUserData {
    /**
     * 
     * @type {Array<ComIbmCommerceOrderFacadeDatatypesRewardOptionTypeUserDataUserDataField>}
     * @memberof ComIbmCommerceOrderFacadeDatatypesRewardOptionTypeUserData
     */
    userDataField?: Array<ComIbmCommerceOrderFacadeDatatypesRewardOptionTypeUserDataUserDataField>;
}


