/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfo } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-fulfillment-schedule-end-info';
import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleFrequencyInfo } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-fulfillment-schedule-frequency-info';
import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleStartInfo } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-fulfillment-schedule-start-info';
import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleUserData } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-fulfillment-schedule-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentSchedule
 */
export interface ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentSchedule {
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfo}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentSchedule
     */
    endInfo?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleEndInfo;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleStartInfo}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentSchedule
     */
    startInfo?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleStartInfo;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleUserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentSchedule
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleUserData;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleFrequencyInfo}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentSchedule
     */
    frequencyInfo?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypeFulfillmentScheduleFrequencyInfo;
}


