/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleFrequencyInfoUserDataUserDataField } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-payment-schedule-frequency-info-user-data-user-data-field';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleFrequencyInfoUserData
 */
export interface ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleFrequencyInfoUserData {
    /**
     * 
     * @type {Array<ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleFrequencyInfoUserDataUserDataField>}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleFrequencyInfoUserData
     */
    userDataField?: Array<ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleFrequencyInfoUserDataUserDataField>;
}


