/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesContactInfoTypeFax1UserData } from './com-ibm-commerce-foundation-common-datatypes-contact-info-type-fax1-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesContactInfoTypeFax1
 */
export interface ComIbmCommerceFoundationCommonDatatypesContactInfoTypeFax1 {
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesContactInfoTypeFax1UserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeFax1
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesContactInfoTypeFax1UserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeFax1
     */
    value: string;
}


