/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest
 */
export interface ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest {
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest
     */
    status?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest
     */
    name?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest
     */
    catEntryId?: number;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest
     */
    requisitionListId?: string;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest
     */
    configurationXML?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest
     */
    partNumber?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest
     */
    type?: number;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceRestRequisitionlistHandlerRequisitionListHandlerRequisitionListConfigurationAddRequest
     */
    quantity?: string;
}


