/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeUserDataUserDataField } from './com-ibm-commerce-order-facade-datatypes-csrcomments-type-user-data-user-data-field';

/**
 * 
 * @export
 * @interface ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeUserData
 */
export interface ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeUserData {
    /**
     * 
     * @type {Array<ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeUserDataUserDataField>}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeUserData
     */
    userDataField?: Array<ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeUserDataUserDataField>;
}


