/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaseRecordIdentifier } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-purchase-record-identifier';
import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-purchased-item-details';
import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddress } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-purchaser-address';
import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypeUserData } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
 */
export interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    lastUpdate?: string;
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddress}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    purchaserAddress?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddress;
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypeUserData}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    userData?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypeUserData;
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    purchasedItemDetails?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    purchaseDate: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    giftListItemID?: string;
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaseRecordIdentifier}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    purchaseRecordIdentifier?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaseRecordIdentifier;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    messageForRegistrant?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    dateCreated?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    registrantMemo?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordType
     */
    noteSent: boolean;
}


