/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeReasonUserDataUserDataField } from './com-ibm-commerce-order-facade-datatypes-promotion-code-type-reason-user-data-user-data-field';

/**
 * 
 * @export
 * @interface ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeReasonUserData
 */
export interface ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeReasonUserData {
    /**
     * 
     * @type {Array<ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeReasonUserDataUserDataField>}
     * @memberof ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeReasonUserData
     */
    userDataField?: Array<ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeReasonUserDataUserDataField>;
}


