/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescriptionOrderExtendAttributeBodyDescription } from './com-ibm-commerce-rest-order-handler-cart-handler-update-order-item-body-description-order-extend-attribute-body-description';
import { ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescriptionOrderItemBodyDescription } from './com-ibm-commerce-rest-order-handler-cart-handler-update-order-item-body-description-order-item-body-description';

/**
 * Description of the updateOrderItem input body.
 * @export
 * @interface ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescription
 */
export interface ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescription {
    /**
     * order extended attribute
     * @type {Array<ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescriptionOrderExtendAttributeBodyDescription>}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescription
     */
    orderExtendAttribute?: Array<ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescriptionOrderExtendAttributeBodyDescription>;
    /**
     * The order ID.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescription
     */
    orderId?: string;
    /**
     * The identifier for the type of calculation to perform on the order.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescription
     */
    x_calculationUsage?: string;
    /**
     * Specifies whether OrderCalculateCmd is called to calculate the charges for the order. 0 = do not call OrderCalculateCmd, 1 = call OrderCalculateCmd.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescription
     */
    x_calculateOrder?: string;
    /**
     * List of order items.
     * @type {Array<ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescriptionOrderItemBodyDescription>}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescription
     */
    orderItem: Array<ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescriptionOrderItemBodyDescription>;
    /**
     * Specifies whether inventory status should be validated for adding to cart.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerUpdateOrderItemBodyDescription
     */
    x_inventoryValidation?: string;
}


