/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCodeDescription } from './com-ibm-commerce-order-facade-datatypes-csrcomments-type-change-reason-code-description';
import { ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCodeUserData } from './com-ibm-commerce-order-facade-datatypes-csrcomments-type-change-reason-code-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCode
 */
export interface ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCode {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCode
     */
    reasonCode?: string;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCodeDescription}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCode
     */
    description?: ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCodeDescription;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCodeUserData}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCode
     */
    userData?: ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCodeUserData;
}


