/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Wish list item body.
 * @export
 * @interface ComIbmCommerceRestWishlistHandlerWishlistHandlerUpdateBodyParameterDescriptionWishlistItemBodyDescription
 */
export interface ComIbmCommerceRestWishlistHandlerWishlistHandlerUpdateBodyParameterDescriptionWishlistItemBodyDescription {
    /**
     * Wish list item quantity requested.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerUpdateBodyParameterDescriptionWishlistItemBodyDescription
     */
    quantityRequested?: string;
    /**
     * Wish list item ID.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerUpdateBodyParameterDescriptionWishlistItemBodyDescription
     */
    giftListItemID: string;
    /**
     * Wish list item product partNumber.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerUpdateBodyParameterDescriptionWishlistItemBodyDescription
     */
    partNumber?: string;
    /**
     * Wish list item product ID.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerUpdateBodyParameterDescriptionWishlistItemBodyDescription
     */
    productId?: string;
}


