/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextBasicInfo } from './com-ibm-commerce-rest-member-handler-user-context-handler-user-context-basic-info';
import { ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextCatalog } from './com-ibm-commerce-rest-member-handler-user-context-handler-user-context-catalog';
import { ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextEntitlement } from './com-ibm-commerce-rest-member-handler-user-context-handler-user-context-entitlement';
import { ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextGlobalization } from './com-ibm-commerce-rest-member-handler-user-context-handler-user-context-globalization';
import { ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreview } from './com-ibm-commerce-rest-member-handler-user-context-handler-user-context-preview';
import { ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextWorkspace } from './com-ibm-commerce-rest-member-handler-user-context-handler-user-context-workspace';

/**
 * User context.
 * @export
 * @interface ComIbmCommerceRestMemberHandlerUserContextHandlerUserContext
 */
export interface ComIbmCommerceRestMemberHandlerUserContextHandlerUserContext {
    /**
     * 
     * @type {ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextBasicInfo}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContext
     */
    basicInfo: ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextBasicInfo;
    /**
     * 
     * @type {ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextEntitlement}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContext
     */
    entitlement: ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextEntitlement;
    /**
     * Is the user partially authenticated.
     * @type {boolean}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContext
     */
    isPartiallyAuthenticated: boolean;
    /**
     * 
     * @type {ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextCatalog}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContext
     */
    catalog: ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextCatalog;
    /**
     * 
     * @type {ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextGlobalization}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContext
     */
    globalization: ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextGlobalization;
    /**
     * 
     * @type {ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextWorkspace}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContext
     */
    workspace?: ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextWorkspace;
    /**
     * 
     * @type {ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreview}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContext
     */
    preview?: ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreview;
}


