/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListResponseItem } from './com-ibm-commerce-rest-wishlist-handler-wishlist-handler-wish-list-response-item';

/**
 * Wish list change response.
 * @export
 * @interface ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListResponse
 */
export interface ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListResponse {
    /**
     * Wish list item to add or update.
     * @type {Array<ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListResponseItem>}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListResponse
     */
    item?: Array<ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListResponseItem>;
    /**
     * The store identifier.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListResponse
     */
    storeId: string;
    /**
     * Wish list unique identifier.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListResponse
     */
    uniqueID: string;
}


