/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAssetAttachmentAssetIdentifier } from './com-ibm-commerce-foundation-common-datatypes-attachment-reference-type-attachment-asset-attachment-asset-identifier';
import { ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAssetStoreIdentifier } from './com-ibm-commerce-foundation-common-datatypes-attachment-reference-type-attachment-asset-store-identifier';
import { ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAssetUserData } from './com-ibm-commerce-foundation-common-datatypes-attachment-reference-type-attachment-asset-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
 */
export interface ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
     */
    mimeType?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAssetAttachmentAssetIdentifier}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
     */
    attachmentAssetIdentifier?: ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAssetAttachmentAssetIdentifier;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
     */
    rootDirectory?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
     */
    language?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
     */
    directoryPath?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAssetStoreIdentifier}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
     */
    storeIdentifier?: ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAssetStoreIdentifier;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
     */
    localAsset?: boolean;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAssetUserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAssetUserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentAsset
     */
    attachmentAssetPath: string;
}


