/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainerMarketingSpotDataTitleContainerMarketingContentImageMapContainerAreaTypeContainer } from './com-ibm-commerce-rest-marketing-handler-espot-data-handler-espot-container-marketing-spot-data-container-marketing-spot-data-title-container-marketing-content-image-map-container-area-type-container';

/**
 * Structure containing image map definition for marketing content.
 * @export
 * @interface ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainerMarketingSpotDataTitleContainerMarketingContentImageMapContainer
 */
export interface ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainerMarketingSpotDataTitleContainerMarketingContentImageMapContainer {
    /**
     * HTML definition of the image map. This element is used when users want to define the whole image map directly using HTML.
     * @type {string}
     * @memberof ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainerMarketingSpotDataTitleContainerMarketingContentImageMapContainer
     */
    source?: string;
    /**
     * Name of the image map.
     * @type {string}
     * @memberof ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainerMarketingSpotDataTitleContainerMarketingContentImageMapContainer
     */
    name?: string;
    /**
     * Clickable area in the image map.
     * @type {Array<ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainerMarketingSpotDataTitleContainerMarketingContentImageMapContainerAreaTypeContainer>}
     * @memberof ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainerMarketingSpotDataTitleContainerMarketingContentImageMapContainer
     */
    area?: Array<ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainerMarketingSpotDataTitleContainerMarketingContentImageMapContainerAreaTypeContainer>;
}


