/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesCouponDescriptionTypeUserData } from './com-ibm-commerce-order-facade-datatypes-coupon-description-type-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceOrderFacadeDatatypesCouponDescriptionType
 */
export interface ComIbmCommerceOrderFacadeDatatypesCouponDescriptionType {
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesCouponDescriptionTypeUserData}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCouponDescriptionType
     */
    userData?: ComIbmCommerceOrderFacadeDatatypesCouponDescriptionTypeUserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCouponDescriptionType
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCouponDescriptionType
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCouponDescriptionType
     */
    longDescription?: string;
}


