/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DisplayPriceIBMStoreDisplayPriceItem } from './display-price-ibmstore-display-price-item';

/**
 * 
 * @export
 * @interface DisplayPriceIBMStoreDisplayPrice
 */
export interface DisplayPriceIBMStoreDisplayPrice {
    /**
     * 
     * @type {number}
     * @memberof DisplayPriceIBMStoreDisplayPrice
     */
    recordSetCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DisplayPriceIBMStoreDisplayPrice
     */
    recordSetComplete?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DisplayPriceIBMStoreDisplayPrice
     */
    recordSetStartNumber?: number;
    /**
     * 
     * @type {Array<DisplayPriceIBMStoreDisplayPriceItem>}
     * @memberof DisplayPriceIBMStoreDisplayPrice
     */
    resultList?: Array<DisplayPriceIBMStoreDisplayPriceItem>;
    /**
     * 
     * @type {number}
     * @memberof DisplayPriceIBMStoreDisplayPrice
     */
    recordSetTotal?: number;
}


