/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EspotCatalogGroupSEOPropertiesParentStoreIdentifier } from './espot-catalog-group-seoproperties-parent-store-identifier';
import { EspotCatalogGroupSEOPropertiesUserData } from './espot-catalog-group-seoproperties-user-data';

/**
 * 
 * @export
 * @interface EspotCatalogGroupSEOProperties
 */
export interface EspotCatalogGroupSEOProperties {
    /**
     * 
     * @type {boolean}
     * @memberof EspotCatalogGroupSEOProperties
     */
    resolved?: boolean;
    /**
     * 
     * @type {EspotCatalogGroupSEOPropertiesUserData}
     * @memberof EspotCatalogGroupSEOProperties
     */
    userData?: EspotCatalogGroupSEOPropertiesUserData;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOProperties
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOProperties
     */
    metaKeyword?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOProperties
     */
    fullImageAltDescription?: string;
    /**
     * 
     * @type {EspotCatalogGroupSEOPropertiesParentStoreIdentifier}
     * @memberof EspotCatalogGroupSEOProperties
     */
    parentStoreIdentifier?: EspotCatalogGroupSEOPropertiesParentStoreIdentifier;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOProperties
     */
    pageGroup?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOProperties
     */
    objectIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOProperties
     */
    sEOPageDefID?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOProperties
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOProperties
     */
    metaDescription?: string;
}


