/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifierExternalIdentifierStoreIdentifier } from './espot-catalog-group-association-catalog-group-reference-catalog-identifier-external-identifier-store-identifier';

/**
 * 
 * @export
 * @interface EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifierExternalIdentifier
 */
export interface EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifierExternalIdentifier {
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifierExternalIdentifier
     */
    ownerID?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifierExternalIdentifier
     */
    identifier: string;
    /**
     * 
     * @type {EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifierExternalIdentifierStoreIdentifier}
     * @memberof EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifierExternalIdentifier
     */
    storeIdentifier?: EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifierExternalIdentifierStoreIdentifier;
}


