/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EspotCatalogGroupAssociationCatalogEntryReferenceCatalogEntryIdentifier } from './espot-catalog-group-association-catalog-entry-reference-catalog-entry-identifier';

/**
 * 
 * @export
 * @interface EspotCatalogGroupAssociationCatalogEntryReference
 */
export interface EspotCatalogGroupAssociationCatalogEntryReference {
    /**
     * 
     * @type {EspotCatalogGroupAssociationCatalogEntryReferenceCatalogEntryIdentifier}
     * @memberof EspotCatalogGroupAssociationCatalogEntryReference
     */
    catalogEntryIdentifier?: EspotCatalogGroupAssociationCatalogEntryReferenceCatalogEntryIdentifier;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupAssociationCatalogEntryReference
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupAssociationCatalogEntryReference
     */
    catalogEntryTypeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupAssociationCatalogEntryReference
     */
    navigationPath?: string;
}


