/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesContractIdentifierType } from './com-ibm-commerce-foundation-common-datatypes-contract-identifier-type';
import { ComIbmCommerceFoundationCommonDatatypesDescriptionType } from './com-ibm-commerce-foundation-common-datatypes-description-type';
import { EspotStandardPriceUserDataField } from './espot-standard-price-user-data-field';
import { EspotStandardUnitPrice } from './espot-standard-unit-price';

/**
 * 
 * @export
 * @interface EspotStandardPrice
 */
export interface EspotStandardPrice {
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesContractIdentifierType}
     * @memberof EspotStandardPrice
     */
    standardPriceContractID?: ComIbmCommerceFoundationCommonDatatypesContractIdentifierType;
    /**
     * 
     * @type {string}
     * @memberof EspotStandardPrice
     */
    standardPriceStartDate?: string;
    /**
     * 
     * @type {number}
     * @memberof EspotStandardPrice
     */
    standardPricePrecedence?: number;
    /**
     * 
     * @type {string}
     * @memberof EspotStandardPrice
     */
    standardPriceQualifier?: string;
    /**
     * 
     * @type {EspotStandardUnitPrice}
     * @memberof EspotStandardPrice
     */
    standardUnitPrice?: EspotStandardUnitPrice;
    /**
     * 
     * @type {number}
     * @memberof EspotStandardPrice
     */
    standardPriceMaxQuantity?: number;
    /**
     * 
     * @type {string}
     * @memberof EspotStandardPrice
     */
    standardPriceEndDate?: string;
    /**
     * 
     * @type {Array<EspotStandardPriceUserDataField>}
     * @memberof EspotStandardPrice
     */
    userDataField?: Array<EspotStandardPriceUserDataField>;
    /**
     * 
     * @type {string}
     * @memberof EspotStandardPrice
     */
    standardPriceLastUpdate?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesDescriptionType}
     * @memberof EspotStandardPrice
     */
    standardPriceDescription?: ComIbmCommerceFoundationCommonDatatypesDescriptionType;
    /**
     * 
     * @type {string}
     * @memberof EspotStandardPrice
     */
    standardPriceQuantityUnit?: string;
    /**
     * 
     * @type {number}
     * @memberof EspotStandardPrice
     */
    standardPriceMinQuantity?: number;
}


