/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceMarketingFacadeDatatypesAreaType } from './com-ibm-commerce-marketing-facade-datatypes-area-type';
import { EspotMarketingContentImageMapUserDataField } from './espot-marketing-content-image-map-user-data-field';

/**
 * 
 * @export
 * @interface EspotMarketingContentImageMap
 */
export interface EspotMarketingContentImageMap {
    /**
     * 
     * @type {string}
     * @memberof EspotMarketingContentImageMap
     */
    source?: string;
    /**
     * 
     * @type {Array<EspotMarketingContentImageMapUserDataField>}
     * @memberof EspotMarketingContentImageMap
     */
    userDataField?: Array<EspotMarketingContentImageMapUserDataField>;
    /**
     * 
     * @type {string}
     * @memberof EspotMarketingContentImageMap
     */
    name?: string;
    /**
     * 
     * @type {Array<ComIbmCommerceMarketingFacadeDatatypesAreaType>}
     * @memberof EspotMarketingContentImageMap
     */
    area?: Array<ComIbmCommerceMarketingFacadeDatatypesAreaType>;
}


