/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface LayoutLayoutItemWidgetWidgetProperty
 */
export interface LayoutLayoutItemWidgetWidgetProperty {
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemWidgetWidgetProperty
     */
    storeId?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemWidgetWidgetProperty
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemWidgetWidgetProperty
     */
    value?: string;
    /**
     * 
     * @type {number}
     * @memberof LayoutLayoutItemWidgetWidgetProperty
     */
    sequence?: number;
}


