/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrganizationRef } from './organization-ref';
import { UserRef } from './user-ref';

/**
 * @type MemberGroupRef
 * The reference to the member group.
 * @export
 */
export type MemberGroupRef = OrganizationRef | UserRef;



