/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderOrderDetailRewardOptionAdjustmentCalculationCodeIDCalculationCodeExternalIdentifier } from './order-order-detail-reward-option-adjustment-calculation-code-idcalculation-code-external-identifier';

/**
 * 
 * @export
 * @interface OrderOrderDetailRewardOptionAdjustmentCalculationCodeID
 */
export interface OrderOrderDetailRewardOptionAdjustmentCalculationCodeID {
    /**
     * 
     * @type {OrderOrderDetailRewardOptionAdjustmentCalculationCodeIDCalculationCodeExternalIdentifier}
     * @memberof OrderOrderDetailRewardOptionAdjustmentCalculationCodeID
     */
    calculationCodeExternalIdentifier?: OrderOrderDetailRewardOptionAdjustmentCalculationCodeIDCalculationCodeExternalIdentifier;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailRewardOptionAdjustmentCalculationCodeID
     */
    uniqueID?: string;
}


