/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderOrderDetailRewardOptionGiftSetGiftItemCatalogEntryIdentifier } from './order-order-detail-reward-option-gift-set-gift-item-catalog-entry-identifier';
import { OrderOrderDetailRewardOptionGiftSetGiftItemQuantity } from './order-order-detail-reward-option-gift-set-gift-item-quantity';

/**
 * 
 * @export
 * @interface OrderOrderDetailRewardOptionGiftSetGiftItem
 */
export interface OrderOrderDetailRewardOptionGiftSetGiftItem {
    /**
     * 
     * @type {OrderOrderDetailRewardOptionGiftSetGiftItemCatalogEntryIdentifier}
     * @memberof OrderOrderDetailRewardOptionGiftSetGiftItem
     */
    catalogEntryIdentifier?: OrderOrderDetailRewardOptionGiftSetGiftItemCatalogEntryIdentifier;
    /**
     * 
     * @type {OrderOrderDetailRewardOptionGiftSetGiftItemQuantity}
     * @memberof OrderOrderDetailRewardOptionGiftSetGiftItem
     */
    quantity?: OrderOrderDetailRewardOptionGiftSetGiftItemQuantity;
}


