/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The Property element definition of a name and value pair.
 * @export
 * @interface Property
 */
export interface Property {
    /**
     * The name of the property.
     * @type {string}
     * @memberof Property
     */
    name?: string;
    /**
     * the value of the property.
     * @type {string}
     * @memberof Property
     */
    value?: string;
}


