/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SegmentSegmentsItem } from './segment-segments-item';

/**
 * 
 * @export
 * @interface SegmentSegments
 */
export interface SegmentSegments {
    /**
     * 
     * @type {number}
     * @memberof SegmentSegments
     */
    recordSetCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SegmentSegments
     */
    recordSetComplete?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SegmentSegments
     */
    recordSetStartNumber?: number;
    /**
     * 
     * @type {Array<SegmentSegmentsItem>}
     * @memberof SegmentSegments
     */
    MemberGroup?: Array<SegmentSegmentsItem>;
    /**
     * 
     * @type {number}
     * @memberof SegmentSegments
     */
    recordSetTotal?: number;
}


