/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Owner } from './owner';

/**
 * The reference to the store.
 * @export
 * @interface StoreRef
 */
export interface StoreRef {
    /**
     * The owners of the store.
     * @type {Array<Owner>}
     * @memberof StoreRef
     */
    owners?: Array<Owner>;
    /**
     * The identifier of the store
     * @type {string}
     * @memberof StoreRef
     */
    name?: string;
}


