/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StorelocatorStorelocatorItemAttribute } from './storelocator-storelocator-item-attribute';
import { StorelocatorStorelocatorItemDescription } from './storelocator-storelocator-item-description';
import { StorelocatorStorelocatorItemUserDataField } from './storelocator-storelocator-item-user-data-field';

/**
 * 
 * @export
 * @interface StorelocatorStorelocatorItem
 */
export interface StorelocatorStorelocatorItem {
    /**
     * 
     * @type {number}
     * @memberof StorelocatorStorelocatorItem
     */
    distance?: number;
    /**
     * 
     * @type {Array<StorelocatorStorelocatorItemDescription>}
     * @memberof StorelocatorStorelocatorItem
     */
    Description?: Array<StorelocatorStorelocatorItemDescription>;
    /**
     * 
     * @type {string}
     * @memberof StorelocatorStorelocatorItem
     */
    storeName?: string;
    /**
     * 
     * @type {Array<StorelocatorStorelocatorItemAttribute>}
     * @memberof StorelocatorStorelocatorItem
     */
    Attribute?: Array<StorelocatorStorelocatorItemAttribute>;
    /**
     * 
     * @type {number}
     * @memberof StorelocatorStorelocatorItem
     */
    longitude?: number;
    /**
     * 
     * @type {string}
     * @memberof StorelocatorStorelocatorItem
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StorelocatorStorelocatorItem
     */
    stateOrProvinceName?: string;
    /**
     * 
     * @type {string}
     * @memberof StorelocatorStorelocatorItem
     */
    uniqueID?: string;
    /**
     * 
     * @type {string}
     * @memberof StorelocatorStorelocatorItem
     */
    telephone1: string;
    /**
     * 
     * @type {number}
     * @memberof StorelocatorStorelocatorItem
     */
    latitude?: number;
    /**
     * 
     * @type {Array<StorelocatorStorelocatorItemUserDataField>}
     * @memberof StorelocatorStorelocatorItem
     */
    userDataField?: Array<StorelocatorStorelocatorItemUserDataField>;
    /**
     * 
     * @type {string}
     * @memberof StorelocatorStorelocatorItem
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof StorelocatorStorelocatorItem
     */
    city?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StorelocatorStorelocatorItem
     */
    addressLine?: Array<string>;
}


