/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Transaction server Services 
 * These services provide APIs to interact with transaction
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WidgetDefinitionConfigurableSlot } from './widget-definition-configurable-slot';
import { WidgetDefinitionDescription } from './widget-definition-description';
import { WidgetDefinitionIBMAdminSummaryItemUserDataField } from './widget-definition-ibmadmin-summary-item-user-data-field';
import { WidgetDefinitionWidgetProperty } from './widget-definition-widget-property';

/**
 * 
 * @export
 * @interface WidgetDefinitionIBMAdminSummaryItem
 */
export interface WidgetDefinitionIBMAdminSummaryItem {
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    widgetObjectName?: string;
    /**
     * 
     * @type {Array<WidgetDefinitionWidgetProperty>}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    widgetProperty?: Array<WidgetDefinitionWidgetProperty>;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    widgetDefinitionId?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    vendor?: string;
    /**
     * 
     * @type {Array<WidgetDefinitionDescription>}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    description?: Array<WidgetDefinitionDescription>;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    widgetType?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    storeId?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    definitionXml?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    path?: string;
    /**
     * 
     * @type {Array<WidgetDefinitionIBMAdminSummaryItemUserDataField>}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    userDataField?: Array<WidgetDefinitionIBMAdminSummaryItemUserDataField>;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    identifier?: string;
    /**
     * 
     * @type {Array<WidgetDefinitionConfigurableSlot>}
     * @memberof WidgetDefinitionIBMAdminSummaryItem
     */
    configurableSlot?: Array<WidgetDefinitionConfigurableSlot>;
}


