apiVersion: apps/v1
kind: Deployment
metadata:
  name: emerald
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: emerald
  template:
    metadata:
      labels:
        app: emerald
    spec:
      containers:
      - image: jonniefivebikes/emerald:latest
        name: emerald
        ports:
        - containerPort: 3000
