apiVersion: apps/v1
kind: Deployment
metadata:
  name: emerald-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: emerald-ui
  template:
    metadata:
      labels:
        app: emerald-ui
    spec:
      containers:
      - image: hub.docker.io/jonniefivebikes/emerald:latest
        name: emerald
        ports:
        - containerPort: 3000
