#!/bin/sh
#
#==================================================
# Licensed Materials - Property of HCL Technologies
#
# HCL Commerce
#
# (C) Copyright HCL Technologies Limited 2021
#
#==================================================
#

. "$(dirname "$0")/_/husky.sh"

npm run pretty-quick -- --staged
./tools/scripts/hooks/lint.sh
