#!/bin/sh
#
#==================================================
# Licensed Materials - Property of HCL Technologies
#
# HCL Commerce
#
# (C) Copyright HCL Technologies Limited 2021
#
#==================================================
#

. "$(dirname "$0")/_/husky.sh"

npx pretty-quick --staged