# This is a basic workflow to help you get started with Actions

name: "HCL AppScan SAST"

# Controls when the action will run. 
on: [push]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  Scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Runs AppScan Step
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.7
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: ${{ secrets.ASOC_APPID }}
        env:
          ASOC_KEY: ${{ secrets.ASOC_KEY }}
          ASOC_SECRET: ${{ secrets.ASOC_SECRET }}
          ASOC_SCAN_NAME: Automated Scan from Github Actions
          ASOC_APPID: ${{ secrets.ASOC_APPID }}
          ASOC_TARGET_DIR: main
          ASOC_WAIT: True
          SONAR_ANALYSIS_BUILDURL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        
  ASOCTrigger:
    name: ASOC CodeSweep Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v1
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
        
        




  
