name: Node.js CI

on: [push]

env:
  CI: false 
  
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false 

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: https://hclcommercestore.jfrog.io/artifactory/api/npm/default-npm-virtual/
        always-auth: true
    - run: npm install
    - run: npm run build
      env:
        CI: false 
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        
        






