name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - env:
       process.env.CI: false 

    - uses: jfrog/setup-jfrog-cli@v1
    - run: jfrog --version


      #- uses: actions/upload-artifact@v3.0.0
      #- name: emerald
      #- path: dist
      #- retention-days: 30
