name: Node.js CI 

on: [push]

env:
  CI: false 
  
jobs:
  build:

    runs-on: ubuntu-18.04
    env:
      CI: false 

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm pack
    
    - name: publish to artifactory
      uses: advancedcsg-open/action-jfrog-cli@master
      with:
        url: 'https://hclcommercestore.jfrog.io/'
        credentials type: 'apikey'
        apikey: ${{ secrets.RT_APIKEY }}
        args: u "*.tgz" "/artifactory/default-generic-local/" --recursive=true --build-name=hcl-commerce-react-store"
    
 
        
        






