name: Sonarqube.js CI 

on: [pullrequest]

env:
  CI: false 
  
jobs:
     
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
        BUILD_NUMBER: ${{ github.run_number }}
        GITHUB_SHA: ${{ github.sha }}
        SONAR_LINKS_CI: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        SONAR_ANALYSIS_BUILDURL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

